import { getPreview } from '../../services/previewStore.service'
import {
  addItemsToPlaylist,
  createPlaylist,
  getCurrentSpotifyUser,
  getSpotifyExportPlaylistPublic,
  removePlaylistFromCurrentUser,
  type SpotifyCreatedPlaylist,
  SpotifyServiceError,
} from '../../services/spotify.service'

const SPOTIFY_ACCESS_TOKEN_COOKIE = 'spotify_access_token'

interface ExportRequest {
  previewId?: unknown
}

export default defineEventHandler(async (event) => {
  const body = await readBody<ExportRequest>(event)
  const previewId = typeof body.previewId === 'string' ? body.previewId : ''
  const accessToken = getCookie(event, SPOTIFY_ACCESS_TOKEN_COOKIE)

  if (!previewId) {
    throw createError({
      statusCode: 400,
      statusMessage: 'PREVIEW_ID_REQUIRED',
    })
  }

  if (!accessToken) {
    throw createError({
      statusCode: 401,
      statusMessage: 'SPOTIFY_AUTH_REQUIRED',
    })
  }

  const preview = getPreview(previewId)

  if (!preview) {
    throw createError({
      statusCode: 404,
      statusMessage: 'PREVIEW_NOT_FOUND',
    })
  }

  const spotifyUris = getExportableSpotifyUris(preview.tracks)

  if (spotifyUris.length === 0) {
    throw createError({
      statusCode: 422,
      statusMessage: 'NO_EXPORTABLE_TRACKS',
    })
  }

  console.info('[spotify-export]', {
    step: 'validated export uris',
    uriCount: spotifyUris.length,
  })

  try {
    const user = await getCurrentSpotifyUser(accessToken)
    const playlist = await createPlaylist(
      accessToken,
      user.id,
      createPlaylistName(preview.targetDurationMs, preview.artist.name),
      createPlaylistDescription(preview.targetDurationMs),
      getSpotifyExportPlaylistPublic(),
    )

    console.info('[spotify-export]', {
      step: 'playlist created',
      playlistId: playlist.id,
      uriCount: spotifyUris.length,
    })

    await addItemsWithCleanup(accessToken, playlist, spotifyUris)

    return {
      spotifyPlaylistId: playlist.id,
      spotifyUrl: playlist.external_urls?.spotify ?? '',
    }
  }
  catch (error: unknown) {
    if (error instanceof SpotifyServiceError) {
      throw createError({
        statusCode: 502,
        statusMessage: error.code,
      })
    }

    throw createError({
      statusCode: 502,
      statusMessage: 'SPOTIFY_EXPORT_ERROR',
    })
  }
})

async function addItemsWithCleanup(
  accessToken: string,
  playlist: SpotifyCreatedPlaylist,
  spotifyUris: string[],
): Promise<void> {
  try {
    await addItemsToPlaylist(accessToken, playlist.id, spotifyUris)
  }
  catch (error: unknown) {
    console.error('[spotify-export]', {
      step: 'add playlist items failed after playlist creation',
      playlistId: playlist.id,
      uriCount: spotifyUris.length,
      cleanupAttempted: true,
    })

    const cleanupSucceeded = await removePlaylistFromCurrentUser(accessToken, playlist.id)

    console.info('[spotify-export]', {
      step: 'playlist cleanup completed',
      playlistId: playlist.id,
      cleanupAttempted: true,
      cleanupSucceeded,
    })

    if (error instanceof SpotifyServiceError) {
      throw new SpotifyServiceError(
        'SPOTIFY_ADD_TRACKS_FORBIDDEN',
        error.message,
      )
    }

    throw new SpotifyServiceError(
      'SPOTIFY_ADD_TRACKS_FORBIDDEN',
      'Spotify refused adding playlist items after playlist creation.',
    )
  }
}

function getExportableSpotifyUris(tracks: Array<{ spotifyUri?: string }>): string[] {
  return [...new Set(
    tracks
      .map(track => track.spotifyUri)
      .filter((spotifyUri): spotifyUri is string =>
        typeof spotifyUri === 'string' && spotifyUri.startsWith('spotify:track:'),
      ),
  )]
}

function createPlaylistName(targetDurationMs: number, artistName: string): string {
  return `${formatDurationMinutes(targetDurationMs)} min ${artistName} playlist · Playlist Timer`
}

function createPlaylistDescription(targetDurationMs: number): string {
  return `Generated by Playlist Timer to last around ${formatDurationMinutes(targetDurationMs)} minutes.`
}

function formatDurationMinutes(durationMs: number): number {
  return Math.round(durationMs / 60_000)
}
